### ISSUE TITLE
publication urls actually contain word "pubication"

### ISSUE THREAD

**Issue by sjn88** [codurance/site#443]
https://codurance.com/pubications/author/mashooq-badar/ 200s but  https://codurance.com/publications/author/mashooq-badar/ 404s 😞

**Comment by jukecraft** [comment]
Probably searching the repository for "pubication" and replacing the wrong redirect definition should fix it

**Comment by sjn88** [comment]
True, but google will still have the wrong word in it, any chance we subscribed to google's site tools and can do the poke for a recache?

**Comment by sjn88** [comment]
...or am I thinking too big and actually a day or so of bad results for a rarely used page is not a big deal here?

**Comment by alvarogarcia7** [comment]
I think the defect comes from here: https://github.com/codurance/site/pull/336/files
